# deploy snapshots to OSS central snapshot repo on push to main

name: build and deploy snapshots to OSS central snapshot repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17

    - name: Build with gradle
      run: ./gradlew clean build javadoc

    - name: Get current artifact version
      run: echo "CURRENT_VERSION=$(./gradlew -q devVersion)" >> $GITHUB_ENV

    - name: Deploy to OSS central snapshot repo
      run: | 
          ./gradlew publish \
            -Puser=${{ secrets.SONATYPE_USER }} \
            -Ppassword=${{ secrets.SONATYPE_PASSWORD }} \
            -PdeployVersion=${{ env.CURRENT_VERSION }}
