# deploy snapshots to OSS central snapshot repo on push to main

name: build and deploy snapshots to OSS central snapshot repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with gradle
      run: ./gradlew clean build javadoc

    - name: Deploy to OSS central snapshot repo
      uses: actions/setup-java@v3
      with:
        java-version: 17
      - name: Get current version
        run: echo "CURRENT_VERSION=$(./gradlew -q devVersion)" >> $GITHUB_ENV
      - name: Deploy
        run:  ./gradlew publish \
              -Puser=${{ secrets.SONATYPE_USER }} \
              -Ppassword=${{ secrets.SONATYPE_PASSWORD }} \
              -PdeployVersion=${{ env.CURRENT_VERSION }}
